services:
  db:
    ports:
      - 5432:5432
    image: postgres:13
    networks:
      - thinkable
    volumes:
      - vol_db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  thinkable:
volumes:
  vol_db: